/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as AuthenticatedMy1rmRouteImport } from './routes/_authenticated/my-1rm'
import { Route as AuthenticatedFeedbackRouteImport } from './routes/_authenticated/feedback'
import { Route as AuthenticatedExercisesRouteImport } from './routes/_authenticated/exercises'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedClientsIndexRouteImport } from './routes/_authenticated/clients.index'
import { Route as AuthenticatedClientsClientIdRouteImport } from './routes/_authenticated/clients.$clientId'
import { Route as AuthenticatedBuilderSessionIdRouteImport } from './routes/_authenticated/builder.$sessionId'
import { Route as AuthenticatedAnalyticsClientIdRouteImport } from './routes/_authenticated/analytics.$clientId'
import { Route as AuthenticatedPlansPlanIdIndexRouteImport } from './routes/_authenticated/plans.$planId.index'
import { Route as AuthenticatedPlansPlanIdBlocksBlockIdRouteImport } from './routes/_authenticated/plans.$planId.blocks.$blockId'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedMy1rmRoute = AuthenticatedMy1rmRouteImport.update({
  id: '/my-1rm',
  path: '/my-1rm',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFeedbackRoute = AuthenticatedFeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedExercisesRoute = AuthenticatedExercisesRouteImport.update({
  id: '/exercises',
  path: '/exercises',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClientsIndexRoute =
  AuthenticatedClientsIndexRouteImport.update({
    id: '/clients/',
    path: '/clients/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClientsClientIdRoute =
  AuthenticatedClientsClientIdRouteImport.update({
    id: '/clients/$clientId',
    path: '/clients/$clientId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBuilderSessionIdRoute =
  AuthenticatedBuilderSessionIdRouteImport.update({
    id: '/builder/$sessionId',
    path: '/builder/$sessionId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAnalyticsClientIdRoute =
  AuthenticatedAnalyticsClientIdRouteImport.update({
    id: '/analytics/$clientId',
    path: '/analytics/$clientId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPlansPlanIdIndexRoute =
  AuthenticatedPlansPlanIdIndexRouteImport.update({
    id: '/plans/$planId/',
    path: '/plans/$planId/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPlansPlanIdBlocksBlockIdRoute =
  AuthenticatedPlansPlanIdBlocksBlockIdRouteImport.update({
    id: '/plans/$planId/blocks/$blockId',
    path: '/plans/$planId/blocks/$blockId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/exercises': typeof AuthenticatedExercisesRoute
  '/feedback': typeof AuthenticatedFeedbackRoute
  '/my-1rm': typeof AuthenticatedMy1rmRoute
  '/invite/$token': typeof InviteTokenRoute
  '/analytics/$clientId': typeof AuthenticatedAnalyticsClientIdRoute
  '/builder/$sessionId': typeof AuthenticatedBuilderSessionIdRoute
  '/clients/$clientId': typeof AuthenticatedClientsClientIdRoute
  '/clients/': typeof AuthenticatedClientsIndexRoute
  '/plans/$planId/': typeof AuthenticatedPlansPlanIdIndexRoute
  '/plans/$planId/blocks/$blockId': typeof AuthenticatedPlansPlanIdBlocksBlockIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/exercises': typeof AuthenticatedExercisesRoute
  '/feedback': typeof AuthenticatedFeedbackRoute
  '/my-1rm': typeof AuthenticatedMy1rmRoute
  '/invite/$token': typeof InviteTokenRoute
  '/analytics/$clientId': typeof AuthenticatedAnalyticsClientIdRoute
  '/builder/$sessionId': typeof AuthenticatedBuilderSessionIdRoute
  '/clients/$clientId': typeof AuthenticatedClientsClientIdRoute
  '/clients': typeof AuthenticatedClientsIndexRoute
  '/plans/$planId': typeof AuthenticatedPlansPlanIdIndexRoute
  '/plans/$planId/blocks/$blockId': typeof AuthenticatedPlansPlanIdBlocksBlockIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/exercises': typeof AuthenticatedExercisesRoute
  '/_authenticated/feedback': typeof AuthenticatedFeedbackRoute
  '/_authenticated/my-1rm': typeof AuthenticatedMy1rmRoute
  '/invite/$token': typeof InviteTokenRoute
  '/_authenticated/analytics/$clientId': typeof AuthenticatedAnalyticsClientIdRoute
  '/_authenticated/builder/$sessionId': typeof AuthenticatedBuilderSessionIdRoute
  '/_authenticated/clients/$clientId': typeof AuthenticatedClientsClientIdRoute
  '/_authenticated/clients/': typeof AuthenticatedClientsIndexRoute
  '/_authenticated/plans/$planId/': typeof AuthenticatedPlansPlanIdIndexRoute
  '/_authenticated/plans/$planId/blocks/$blockId': typeof AuthenticatedPlansPlanIdBlocksBlockIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/dashboard'
    | '/exercises'
    | '/feedback'
    | '/my-1rm'
    | '/invite/$token'
    | '/analytics/$clientId'
    | '/builder/$sessionId'
    | '/clients/$clientId'
    | '/clients/'
    | '/plans/$planId/'
    | '/plans/$planId/blocks/$blockId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/dashboard'
    | '/exercises'
    | '/feedback'
    | '/my-1rm'
    | '/invite/$token'
    | '/analytics/$clientId'
    | '/builder/$sessionId'
    | '/clients/$clientId'
    | '/clients'
    | '/plans/$planId'
    | '/plans/$planId/blocks/$blockId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/dashboard'
    | '/_authenticated/exercises'
    | '/_authenticated/feedback'
    | '/_authenticated/my-1rm'
    | '/invite/$token'
    | '/_authenticated/analytics/$clientId'
    | '/_authenticated/builder/$sessionId'
    | '/_authenticated/clients/$clientId'
    | '/_authenticated/clients/'
    | '/_authenticated/plans/$planId/'
    | '/_authenticated/plans/$planId/blocks/$blockId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  InviteTokenRoute: typeof InviteTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/my-1rm': {
      id: '/_authenticated/my-1rm'
      path: '/my-1rm'
      fullPath: '/my-1rm'
      preLoaderRoute: typeof AuthenticatedMy1rmRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/feedback': {
      id: '/_authenticated/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof AuthenticatedFeedbackRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/exercises': {
      id: '/_authenticated/exercises'
      path: '/exercises'
      fullPath: '/exercises'
      preLoaderRoute: typeof AuthenticatedExercisesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clients/': {
      id: '/_authenticated/clients/'
      path: '/clients'
      fullPath: '/clients/'
      preLoaderRoute: typeof AuthenticatedClientsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clients/$clientId': {
      id: '/_authenticated/clients/$clientId'
      path: '/clients/$clientId'
      fullPath: '/clients/$clientId'
      preLoaderRoute: typeof AuthenticatedClientsClientIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/builder/$sessionId': {
      id: '/_authenticated/builder/$sessionId'
      path: '/builder/$sessionId'
      fullPath: '/builder/$sessionId'
      preLoaderRoute: typeof AuthenticatedBuilderSessionIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/analytics/$clientId': {
      id: '/_authenticated/analytics/$clientId'
      path: '/analytics/$clientId'
      fullPath: '/analytics/$clientId'
      preLoaderRoute: typeof AuthenticatedAnalyticsClientIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/plans/$planId/': {
      id: '/_authenticated/plans/$planId/'
      path: '/plans/$planId'
      fullPath: '/plans/$planId/'
      preLoaderRoute: typeof AuthenticatedPlansPlanIdIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/plans/$planId/blocks/$blockId': {
      id: '/_authenticated/plans/$planId/blocks/$blockId'
      path: '/plans/$planId/blocks/$blockId'
      fullPath: '/plans/$planId/blocks/$blockId'
      preLoaderRoute: typeof AuthenticatedPlansPlanIdBlocksBlockIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedExercisesRoute: typeof AuthenticatedExercisesRoute
  AuthenticatedFeedbackRoute: typeof AuthenticatedFeedbackRoute
  AuthenticatedMy1rmRoute: typeof AuthenticatedMy1rmRoute
  AuthenticatedAnalyticsClientIdRoute: typeof AuthenticatedAnalyticsClientIdRoute
  AuthenticatedBuilderSessionIdRoute: typeof AuthenticatedBuilderSessionIdRoute
  AuthenticatedClientsClientIdRoute: typeof AuthenticatedClientsClientIdRoute
  AuthenticatedClientsIndexRoute: typeof AuthenticatedClientsIndexRoute
  AuthenticatedPlansPlanIdIndexRoute: typeof AuthenticatedPlansPlanIdIndexRoute
  AuthenticatedPlansPlanIdBlocksBlockIdRoute: typeof AuthenticatedPlansPlanIdBlocksBlockIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedExercisesRoute: AuthenticatedExercisesRoute,
  AuthenticatedFeedbackRoute: AuthenticatedFeedbackRoute,
  AuthenticatedMy1rmRoute: AuthenticatedMy1rmRoute,
  AuthenticatedAnalyticsClientIdRoute: AuthenticatedAnalyticsClientIdRoute,
  AuthenticatedBuilderSessionIdRoute: AuthenticatedBuilderSessionIdRoute,
  AuthenticatedClientsClientIdRoute: AuthenticatedClientsClientIdRoute,
  AuthenticatedClientsIndexRoute: AuthenticatedClientsIndexRoute,
  AuthenticatedPlansPlanIdIndexRoute: AuthenticatedPlansPlanIdIndexRoute,
  AuthenticatedPlansPlanIdBlocksBlockIdRoute:
    AuthenticatedPlansPlanIdBlocksBlockIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  InviteTokenRoute: InviteTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
